### ISSUE TITLE
Provide a Generic way to test all koan style exercises once and for all

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#276]
There is currently no unit tests for the koan style exercises in the Stdlib.
https://github.com/47deg/scala-exercises/tree/version-2/site/content/src/main/exercises/stdlib

Ideally we would use property testing in these cases generating arbitrary instances of the params that do not match expected results to ensure it fails with all expressions not expected and pass with the expected ones. I wonder if we can abstract over arity with shapeless here to provide something like:

```scala
forAll { e : ErroringParams[ExerciseMethod] =>
     (exerciseMethod _).tupled(e.getParams)
}
```

**Comment by raulraja** [comment]
We could also encapsulate this pattern in some kind of helper that auto tests an exercise so authors can simply add...
```scala
checkExercise[ExerciseMethod](success = 1::3::"whatever"::HNil)
```

**Comment by dialelo** [comment]
Just to make sure I understand it, the `checkExercise` method would receive an HList with the right answers and call the method ensuring that it runs perfectly with those parameters. Also, it should generate arbitrary answers that aren't right (given that we know the right answers) and ensure that the method fails in those cases, right?

**Comment by raulraja** [comment]
Yes that is the idea!
