### ISSUE TITLE
Move exercises to src/main/scala

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#303]
Looks like neither Ensime nor IntelliJ is able to find exercises as valid Scala sources when placed in `src/main/exercises`. Furthermore Scalariform is not getting applied to those paths. This makes the process of writting exercises extremely painful and error prone manually formatting and not getting any editor help.
Ideally exercises should live in /src/main/scala as any other source or a location where Ensime and IDEA are able to treat them as any ordinary scala source.

Let's give this priority after resolving the issues with #259. @dialelo and myself are writing exercises and would love to have this ASAP.

**Comment by andyscott** [comment]
I'll see what I can do. It's not a very difficult change, but I'm addressing #259 first.
