### ISSUE TITLE
 Evaluation failed : doobie.util.invariant$UnexpectedContinuation$: Expected ResultSet exhaustion, but more rows were available.

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#305]
It appears that when saving the user input in the DB we are violating or not enforcing the uniqueness constraint of having a single entry per user input for a given exercise:

Evaluation failed : doobie.util.invariant$UnexpectedContinuation$: Expected ResultSet exhaustion, but more rows were available.

Also the exception seems swallowed and no stack trace is available.

**Comment by WizzieP** [comment]
@raulraja @dialelo I'm getting this error right now.

I've logged in, did one std exercise, then came back to main page. Now i'm clicking on "std" again to do another exercises and I get a white page saying: "Expected ResultSet exhaustion, but more rows were available.". Cats and shapeless subpages work well.
