### ISSUE TITLE
The exercise libraries are no longer found when running the server

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#322]
After merging #321 it seems that, even after compiling the `content` subproject, exercise libraries are not being found when running the server. @andyscott am i doing something wrong?

![no-libs](https://cloud.githubusercontent.com/assets/409039/14138862/cc5ae99c-f66f-11e5-9033-8ef7587b6ec2.png)

**Comment by andyscott** [comment]
I believe I mistakenly forgot to commit the ivy mapping from "CompileGeneratedExercises" to default when site depends on content.

**Comment by andyscott** [comment]
See #325.
