### ISSUE TITLE
Pass a tuple instead an HList to the exercise solution tests

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#323]
Currently the exercises are tested passing a method reference and an HList with the right answer. It'd be nicer if instead of an HList we could simply pass a tuple with the right answers for saving the HList boilerplate. This way, the following code:

```scala
  def `has a combine operation` = {
    check(
      Test.testSuccess(
        SemigroupSection.semigroupCombine _,
        3 :: List(1, 2, 3, 4, 5, 6) :: Option(3) :: Option(1) :: 67 :: HNil
      )
    )
  }
```

would look like:

```scala
  def `has a combine operation` = {
    check(
      Test.testSuccess(
        SemigroupSection.semigroupCombine _,
        (3, List(1, 2, 3, 4, 5, 6), Option(3), Option(1), 67)
      )
    )
  }
```

**Comment by jdesiloniz** [comment]
This should be done as a part of #324, closing this as a duplicate ticket.
