### ISSUE TITLE
Compilation error: Unable to evaluate arg Option(1) as scala.Option[scala.Int]

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#332]
This is still happening in all libraries. The evaluator is somehow broken and yields inconsistent evaluations after the imports where auto discovered.

I think for the time being we just need to specify per section which imports will be provided for user input to be evaluated against.

This is a high priority as it prevents from evaluating exercises.

![sc](https://cloud.githubusercontent.com/assets/456796/14203732/08dafa4c-f800-11e5-95c7-bb517c2c73f0.png)

**Comment by raulraja** [comment]
@andyscott Was this already taken care of? let me know so we can close this issue. thanks!

**Comment by andyscott** [comment]
I believe it was addressed-- we should double check before closing this!

**Comment by raulraja** [comment]
I can't repro it so we'll reopen it if it comes back.
