### ISSUE TITLE
Add exercises from the "Functional Programming in Scala" book?

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#339]
The [Functional Programming in Scala book](https://www.manning.com/books/functional-programming-in-scala) teaches FP in Scala from first principles, challenging readers with plenty of exercises that help build their understanding. We could add the exercises from the book (if the authors agree) to a library in Scala Exercises so readers of the book can track their progress and have their answers automatically checked.

I think this can be a very natural next step for people introduced to Scala through the Standard Library exercises, as well as building a solid foundation to tackle the Cats and Shapeless exercises.

**Comment by rafaparadela** [comment]
Nice. @raulraja Could you ask Runar if they agree, please?

**Comment by raulraja** [comment]
I got positive word from Runar but we need to ask O'Reilly if they'd be ok with it. Ultimately we would drive traffic and sales back to them so I don't foresee a problem. Perhaps @nickelsberry can reach out to them.

**Comment by juanpedromoreno** [comment]
Exercises included in this PR https://github.com/scala-exercises/scala-exercises/pull/578
