### ISSUE TITLE
Add Guillaume to the scala-exercises team on GitHub

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#354]
We should add @MasseGuillaume as a colaborator of the repository. @raulraja I can invite him as soon as you give me the green light! :vertical_traffic_light:

**Comment by raulraja** [comment]
:green_heart: Welcome @MasseGuillaume!

**Comment by dialelo** [comment]
Done, @MasseGuillaume you now have write access to this repo.
