### ISSUE TITLE
Compile-time checking of expressions in an exercise? 

### ISSUE THREAD

**Issue by oranda** [scala-exercises/scala-exercises#393]
I went though the Shapeless and Cats exercises today, and learnt a lot, especially from the Cats ones. I think these exercises will do a lot that is needed to popularize typelevel libraries.

One thing I noticed. The exercises as they stand are oriented to checking result values of expressions. But what if an expression doesn't compile at all? Shapeless in particular has a penchant for cutting you off at compile-time :wink: For instance if you put this in an exercise:

```scala
illTyped { """1+1 : Int""" }
```

... the whole build will fail.

**Comment by oranda** [comment]
Scalatest can check if expressions compile with  `assertTypeError` and `shouldNot compile` so perhaps these could be used.

**Comment by raulraja** [comment]
@oranda Makes sense, wanna take a shot at one of the exercises you think that could be improved?

**Comment by oranda** [comment]
OK, I'll have a quick try.

James

**Comment by raulraja** [comment]
Also now that the content modules are independent you will have to do a `sbt clean compile publishLocal` in the exercises module before the `site` modules sees any changes. We are moving toward distributed exercises modules that any library can host on their own and this interim annoyance is required to see content in the site while developing locally.

**Comment by oranda** [comment]
OK thanks, good to know.

James
