### ISSUE TITLE
Disable non-ssl connections in Prod

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#412]
We need to disable non-sl connections in production.

Something in these lines from http://stackoverflow.com/questions/19147147/how-to-force-play-framework-2-to-always-use-ssl ...
```scala
object HttpsAction extends ActionBuilder[Request] with Results {
    def invokeBlock[A](request: Request[A], block: (Request[A]) => Future[Result]) = {
        if (Play.isProd && !request.secure) {
            Future.successful(Redirect(s"https://${request.domain}:443${request.path}", 301))
        } else {
            block(request)
        }
    } 
}
```

**Comment by dialelo** [comment]
Note that we need to update the URL in the GitHub application of Scala Exercises. It should be https and not http, is currently failing. @rafaparadela please take a look.

**Comment by rafaparadela** [comment]
@dialelo that is done. However we need to enforce https connection in order to avoid issue #432

**Comment by dialelo** [comment]
On it.
