### ISSUE TITLE
Shapeless exercises not compiling

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#431]
Seems like something is wrong with the imports fix that now some exercises are not compiling.

https://www.scala-exercises.org/shapeless/polymorphic_function_values
Compilation error: compilation error not found: object poly

**Comment by dialelo** [comment]
Should be working now, @raulraja can you confirm?

**Comment by rafaparadela** [comment]
I have checked, it's working properly in prod.
