### ISSUE TITLE
"Expected ResultSet exhaustion, but more rows were available."

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#435]
From @WizzieP in the Gitter channel:

>I've logged in, did one std exercise, then came back to main page. Now i'm clicking on "std" again to do another exercises and I get a white page saying: "Expected ResultSet exhaustion, but more rows were available."
>found this issue: "scala-exercises/scala-exercises#305" but it's closed

Looks like #305 is not fully solved. Investigating it.

**Comment by rafaparadela** [comment]
Fixed by #436
