### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#442]
We need to provide a dynamic site-map based on the content for proper indexing.

**Comment by rafaparadela** [comment]
@raulraja Do you know this plugin? http://edulify.github.io/play-sitemap-module.edulify.com/

If looks good to you, I can integrate it.

**Comment by raulraja** [comment]
Let's give it a shot and see what it produces!

**Comment by andyscott** [comment]
That plugin looks like it periodically regenerates a sitemap. We might be able to utilize some parts of the plugin's codebase and just generate the entire site map, since we know all of the exercises the corresponding urls.

**Comment by raulraja** [comment]
Let's not use this plugin. Looking at the examples it's gonna be easier to render a template for the site map iterating ourselves over the library and exercises lists. We don't want to annotate or create a bunch of new controller methods to just add the site map.
