### ISSUE TITLE
Exercise evaluation is not done if a previously evaluated answer is used again

### ISSUE THREAD

**Issue by justinelsberry** [scala-exercises/scala-exercises#459]
If you answer an exercise, change it and the go back to any previous answer the exercise is not re-evaluated. Using the first exercise in the stdlib as an example:

true should be(___)

Repro steps:

1. Type 'true' in the exercise blank and hit Enter
2. The exercise is evaluated as correct and highlighted green
3. Clear your previous answer and type 'false' and hit Enter
4. The exercise is evaluated as incorrect and failed assertion shown
5. Clear your previous answer and type 'true' and hit Enter
6. The exercise is not evaluated

Expected result:
The exercise should be re-evaluated even if the user typed that answer in past evaluations.

Appears to be a client side issue as refreshing the page clears the state and you can re-evaluate the exercise with a past answer.

**Comment by dialelo** [comment]
Very detailed issue, thanks a lot @justinelsberry. I'll take a look ASAP.
