### ISSUE TITLE
Sbt Run successfull and app gets started but when I try to load the app it fails

### ISSUE THREAD

**Issue by CaRthY5532** [scala-exercises/scala-exercises#460]
Hi all, 

I've installed all dependencies and I ran sbt run. app started but when I check the URL, it give me "Java Heap Space" message and thats all it does. 

I'm trying to increase the JVM heap space but not sure how to change for this app. Please help. Thanks

**Comment by raulraja** [comment]
@CaRthY5532 we are currently using the following JAVA_OPTS settings in Heroku. `-Xmx768m -Xss512k -XX:+UseCompressedOops`. Something in those lines should work.

**Comment by raulraja** [comment]
Locally I have this:
```
workspace/scala-exercises/site sbt -v                                  rr-enforce-www :: 0h26m :: ⬡
[process_args] java_version = '1.8.0_01-Ubuntu'
# Executing command line:
java
-Xms2048m
-Xmx2048m
-XX:ReservedCodeCacheSize=256m
-XX:MaxMetaspaceSize=512m
-jar
/usr/share/sbt-launcher-packaging/bin/sbt-launch.jar
```

Keep in mind that locally play has to compile an use a lot of memory for live reloading
