### ISSUE TITLE
Site goes down when rate limited by Github

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#475]
@justinelsberry experienced today a case while navigating. All the sudden he saw a github rate limit message and the whole site went down. looks like we still have some lingering github accesses happening on the site post compilation causing this issue. He reloaded the site in incognito mode with the same results.

**Comment by justinelsberry** [comment]
![screen shot 2016-06-27 at 2 12 10 pm](https://cloud.githubusercontent.com/assets/205617/16395946/473887f4-3c71-11e6-8475-ed107da735a0.png)

**Comment by justinelsberry** [comment]
Just hit refresh about 20 times on the homepage and then that error was displayed

**Comment by raulraja** [comment]
This is a release blocker as with the increasing number of users in the announcement we can see ourselves easily in the same situation. Are we perhaps calling github auth on each request instad of caching the user's credentials in the cookie?

**Comment by dialelo** [comment]
I've detected a couple calls to GitHub without using the user's access token, thus unauthenticated and subject to rate limiting. Wil fix this tomorrow morning.
