### ISSUE TITLE
The "Spread the word" call to action is a broken link

### ISSUE THREAD

**Issue by dialelo** [scala-exercises/scala-exercises#493]
The call to action in the "Spread the word" button in the homepage has an empty link, shouldn´t it be a link to share the website on twitter or facebook? @raulraja let me know your thoughts.

**Comment by raulraja** [comment]
Must of have broken recently because back then I submitted some link fixes
and tested it worked if I recall correctly. Yes we need that to share via
Twitter at a minimum.

**Comment by dialelo** [comment]
Nevermind, it works perfectly and shows a modal to share in various social networks. The problem must have been between the keyboard and the chair :stuck_out_tongue:
