### ISSUE TITLE
Content Independent Classloaders

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#501]
As new content is getting added to Scala Exercises we are starting to hit the limitation of sharing the Classloader of the server with the Evaluator. We need a per library class loader so we can have separate classpaths per content module. 
This will enable us to have:
- [ ] Separate lib versions in exercises (Ex. content : Doobie 0.1.x, site : Doobie 0.2.x).
- [ ] Avoid eviction of libs that can cause runtime failures when evaluating binary incompatible lib versions.

@andyscott you are the most experienced one in that are and would love if you can take up on this task. @franciscodr and others are already starting to create exercises for libs like Doobie which will cause inmediate classpath conflicts as soon as they are released.

**Comment by andyscott** [comment]
Sounds good! I'll begin working on it shortly.

**Comment by raulraja** [comment]
This was addressed by @dialelo as part of the Remote Evaluator work and it's now live since #543 was fixed on #571
