### ISSUE TITLE
Show better errors, i.e. line numbers

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#509]
_From @hejfelix on July 3, 2016 15:2_

It would be a _huge_ improvement if the quizzes would give a position (which line was the failed assertion?). I appreciate, that in this way, we are not getting the answers, but maybe as an easy fix, split each line into it's own box to make locating your mistakes much easier.

_Copied from original issue: scala-exercises/exercises-cats#27_

**Comment by raulraja** [comment]
@andyscott Do you think we can point out the line where the failed assertions happen ^^^

**Comment by dialelo** [comment]
Dupe of #437?

**Comment by raulraja** [comment]
Yep @hejfelix closing this in favor of #437. @andyscott let's continue the conversation there.
