### ISSUE TITLE
Show "Library XYZ: Coming Soon" tiles

### ISSUE THREAD

**Issue by andyscott** [scala-exercises/scala-exercises#513]
On the main index page, it would be useful if we showed a tile for libraries that are coming soon. The tiles would be the same size/shape as the current library tiles, but they could be grayed out. Clicking a contribute icon on the tile could link you to a the repo for that work-in-progress library.

Thoughts?

**Comment by dialelo** [comment]
I like the idea! :+1:

**Comment by rafaparadela** [comment]
Totally. Great idea because, in fact, some awesome libraries are coming.

**Comment by andyscott** [comment]
@rafaparadela That's exactly how I had this "idea"!

@israelperezglez Any idea how difficult it would be to get a "coming soon" tile design?

**Comment by israelperezglez** [comment]
Is easy. Tomorrow I will coordinate with @jorgegalindocruces or @raulraja for implement this idea ;)
