### ISSUE TITLE
Library logo images are not part of the content modules

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#520]
The content modules via the Library trait impl should provide references to the files where the library content logo image is located. Currently it's located in the site.

**Comment by jdesiloniz** [comment]
@raulraja @israelperezglez I have this mostly laid out, but I think it'd be a good idea to have a default logo for those libraries that don't come with a correct logo location. What are your thoughts about it?

**Comment by israelperezglez** [comment]
@jdesiloniz I attach the icon

[scala_exercises.svg.zip](https://github.com/scala-exercises/scala-exercises/files/461111/scala_exercises.svg.zip)
