### ISSUE TITLE
Compilation error: java.lang.AssertionError: assertion failed

### ISSUE THREAD

**Issue by timjstewart** [scala-exercises/scala-exercises#522]
Any time I enter a value and press "Run", I get:

Compilation error: java.lang.AssertionError: assertion failed: (15,12)

Unless it's really a test to see if I can fix the bug...  :)

**Comment by raulraja** [comment]
@timjstewart Thanks for reporting it. looks like the evaluator goes into some inconsistent state after hours of work. By all means if you have any idea of what is going on PRs are welcome!. We restarted the server and it's back to normal. @MasseGuillaume have you seen this before?

**Comment by raulraja** [comment]
Logs indicate all evaluations result in the same exception
```
Jul 07 00:52:46 scala-exercises app/web.1: 07:52:46.593 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.valuesAsserts,1,Koans,List(2)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:53:39 scala-exercises app/web.1: 07:53:39.267 [pool-7-thread-1] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.scalaTestAsserts,1,Koans,List(true)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:53:45 scala-exercises app/web.1: 07:53:44.778 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.scalaTestAsserts,1,Koans,List(true)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:53:48 scala-exercises app/web.1: 07:53:48.375 [pool-7-thread-1] INFO  application - evaluation for ExerciseEvaluation(std_lib,partially_applied_functions,stdlib.PartiallyAppliedFunctions.partiallyAppliedPartiallyAppliedFunctions,1,Koans,List(17, 15)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:53:51 scala-exercises app/web.1: 07:53:51.333 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.scalaTestAsserts,1,Koans,List(true)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:54:19 scala-exercises app/web.1: 07:54:19.625 [pool-7-thread-1] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.booleanAsserts,1,Koans,List(4)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:54:22 scala-exercises app/web.1: 07:54:22.614 [pool-7-thread-1] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.booleanAsserts,1,Koans,List(4)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:54:25 scala-exercises app/web.1: 07:54:24.943 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,maps,stdlib.Maps.removedWithTupleMaps,1,Koans,List(false, true, true, 2, 4)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:54:41 scala-exercises app/web.1: 07:54:40.802 [pool-7-thread-1] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.scalaTestAsserts,1,Koans,List(true)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:55:05 scala-exercises app/web.1: 07:55:04.894 [pool-7-thread-1] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.scalaTestAsserts,1,Koans,List(true)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:55:11 scala-exercises app/web.1: 07:55:11.219 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.valuesAsserts,1,Koans,List(2)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:55:50 scala-exercises app/web.1: 07:55:49.893 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,pattern_matching,stdlib.PatternMatching.againstListsPatternMatching,1,Koans,List(4)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:56:08 scala-exercises app/web.1: 07:56:08.398 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,pattern_matching,stdlib.PatternMatching.againstListsPatternMatching,1,Koans,List(12)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
Jul 07 00:56:19 scala-exercises app/web.1: 07:56:18.955 [pool-7-thread-2] INFO  application - evaluation for ExerciseEvaluation(std_lib,asserts,stdlib.Asserts.scalaTestAsserts,1,Koans,List(true)): Left(Compilation error: java.lang.AssertionError: assertion failed: (15,12)) 
```

**Comment by MasseGuillaume** [comment]
It's possible that the compiler can crash. One thing we could do is to have a heartbeat monitor like evaluating `1 + 1` and asserting the result is `2`. If it's something else, restart the compiler. The issue with this is that a user can run the same code again an crash the compiler again (sometime not maliciously).

**Comment by raulraja** [comment]
@MasseGuillaume It turns out the `Evaluator` class  is also non thread safe. What is happening is that the classloader and internal state is getting reset prior to evaluation but the class instance is unique for the whole app so we are causing people tripping on each others feet as they evaluate exercises leaving the compiler in an unusable state. For now we are gonna synchronize access to the `Evaluator#apply` but we are gonna need a long term solution since it goes down every few hours as is.

https://github.com/scala-exercises/scala-exercises/blob/389af5e949b591359485e899c981cc77f314c79d/runtime/src/main/scala/org/scalaexercises/exercises/MethodEval.scala#L67

https://github.com/scala-exercises/scala-exercises/blob/389af5e949b591359485e899c981cc77f314c79d/runtime/src/main/scala/org/scalaexercises/exercises/Evaluator.scala#L252

https://github.com/scala-exercises/scala-exercises/blob/389af5e949b591359485e899c981cc77f314c79d/runtime/src/main/scala/org/scalaexercises/exercises/Evaluator.scala#L216

https://github.com/scala-exercises/scala-exercises/blob/389af5e949b591359485e899c981cc77f314c79d/runtime/src/main/scala/org/scalaexercises/exercises/Evaluator.scala#L220

**Comment by raulraja** [comment]
@MasseGuillaume this is the temporary workaround. https://github.com/scala-exercises/scala-exercises/pull/528

Synchronizing this code though has a major problem which is if someone tries to eval something malicious like an endless loop or something where we are relying in the timeout then other users are gonna have to wait for the evaluation to proceed.

**Comment by rafaparadela** [comment]
Fixed
