### ISSUE TITLE
Add SVG logos for all incoming exercises Libs

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#524]
- [x] Scalacheck
- [x] Doobie
- [x] FPis
- [x] Circe

**Comment by raulraja** [comment]
@jorgegalindocruces Here is the issue for the logos we spoke about in person ^^^

**Comment by jorgegalindocruces** [comment]
- ScalaCheck - We will add a review of the logo in B/W
- Doobie - Please @franciscodr can you contact with the author? Can you ask for the logo and in the case that they has not any logo, can you mention me in the channel to talk about that? Thanks! 
- FPis - @israelperezglez, we will do in this case a logo of a Book with the letters FP inside.
- Circe - I will contact with Travis, I have him in Twitter and he follows me, we can talk in DM.

**Comment by jorgegalindocruces** [comment]
FYK: We contacted with Travis and Rob Norris by the official channels in Gitter. To follow the conversation join the chat :-)

**Comment by israelperezglez** [comment]
I attach all logos in svg format @jdesiloniz 

[Circe.svg.zip](https://github.com/scala-exercises/scala-exercises/files/418719/Circe.svg.zip)

[Doobie.svg.zip](https://github.com/scala-exercises/scala-exercises/files/418720/Doobie.svg.zip)

[FPis.svg.zip](https://github.com/scala-exercises/scala-exercises/files/418722/FPis.svg.zip)

[ScalaCheck.svg.zip](https://github.com/scala-exercises/scala-exercises/files/418725/ScalaCheck.svg.zip)

**Comment by juanpedromoreno** [comment]
These logos were added in the PR #571 .
