### ISSUE TITLE
Don't let people inject evil code

### ISSUE THREAD

**Issue by anadoba** [scala-exercises/scala-exercises#540]
I was actually learning, but my friend came up and said `Why don't we try putting some code there?`

so when the exercise looked roughly like this

```
val some = Some(123)

some.get shouldEqual _____    <- type something here
```

I put
`{ while (true) {}; 123 }`

Unfortunately server went down while testing 👯 
Looks like the whole website is down on `Application Error` title and `404` page.
I'm sorry :)

**Comment by dialelo** [comment]
It's because yesterday we replaced the problematic evaluation code with Twitter's eval and we are not respecting timeouts now, working to fix it. Thanks for reporting :blush:
