### ISSUE TITLE
Move the Evaluator to it's own process

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#543]
Currently the evaluator is in process and in the same classpath as the rest of libraries which makes it easy to inject malicious code through exercises params. See #540.

**Comment by andyscott** [comment]
I also am interested in working on this. I'll be free next week (presumably).

**Comment by raulraja** [comment]
Sounds good Andy, we are moving stuff now but there is plenty of stuff to
do there now that we are gonna bring gist support soon and the evaluator
will become a standalone piece used in other projects potentially.

**Comment by raulraja** [comment]
This was completed as part of #571 but we still have some security concerns regarding injection of code #540
