### ISSUE TITLE
Move Test Class Helper to the sbt-exercises Plugin

### ISSUE THREAD

**Issue by juanpedromoreno** [scala-exercises/scala-exercises#546]
At this moment, all the new exercise modules are replicating the Test class helper to test the exercises:

https://github.com/scala-exercises/exercises-cats/blob/master/src/test/scala/exercises/Test.scala
https://github.com/scala-exercises/exercises-shapeless/blob/master/src/test/scala/exercises/Test.scala
https://github.com/scala-exercises/exercises-stdlib/blob/master/src/test/scala/exercises/Test.scala
etc.

We could move it to a common place like the `sbt-exercises` plugin.

Does it make sense @raulraja @dialelo ?

**Comment by raulraja** [comment]
Yep, this is a dup of #510. Closing this and assigning that to you! ;)
