### ISSUE TITLE
New Library Design Specs

### ISSUE THREAD

**Issue by juanpedromoreno** [scala-exercises/scala-exercises#547]
Contributors who want to include new libraries need to know all the specifics about the design:

* Logo requirements
* Styles if it's needed
* Etc.

This information will be attached to the developer guide.

Please, @israelperezglez  could you provide all the needed information? Thanks!

**Comment by israelperezglez** [comment]
Logo

- SVG
- White
- Square ratio

Style

- Corporate color

**Comment by juanpedromoreno** [comment]
Thanks @israelperezglez !
