### ISSUE TITLE
Library with nested packages not allowed

### ISSUE THREAD

**Issue by juanpedromoreno** [scala-exercises/scala-exercises#554]
When defining a new library, this should be placed on one-level package deep, multi-level deep is not allowed by the Scala Exercises compiler.

Therefore, at this moment, we could have package `pkg` but not package `com.company.pkg`.

@dialelo @raulraja Does this issue make sense?

**Comment by dialelo** [comment]
I think we should allow whatever package structure the exercise writers want.
