### ISSUE TITLE
Running locally not showing libraries - std, cats and shapeless listing

### ISSUE THREAD

**Issue by pawank** [scala-exercises/scala-exercises#560]
Hello,

"sbt run" shows below warning messages (showing tail of many such)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:35: Inferred type containing Product
[warn] GET /progress/library/:libraryName/section/:sectionName org.scalaexercises.exercises.controllers.UserProgressController.fetchUserProgressBySection(libraryName: String, sectionName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:35: Inferred type containing Serializable
[warn] GET /progress/library/:libraryName/section/:sectionName org.scalaexercises.exercises.controllers.UserProgressController.fetchUserProgressBySection(libraryName: String, sectionName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:35: Inferred type containing Serializable
[warn] GET /progress/library/:libraryName/section/:sectionName org.scalaexercises.exercises.controllers.UserProgressController.fetchUserProgressBySection(libraryName: String, sectionName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:9: Inferred type containing Serializable
[warn] GET /loaderio-:token/ org.scalaexercises.exercises.controllers.LoaderIOController.verificationToken(token: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:14: Inferred type containing Serializable
[warn] GET /users/:login org.scalaexercises.exercises.controllers.UserController.byLogin(login: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:16: Inferred type containing Serializable
[warn] POST /exercises/sections/:libraryName/:sectionName/evaluate org.scalaexercises.exercises.controllers.ExercisesController.evaluate(libraryName: String, sectionName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:20: Inferred type containing Serializable
[warn] GET /assets/*file controllers.Assets.at(path="/public", file)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:31: Inferred type containing Serializable
[warn] GET /:libraryName               org.scalaexercises.exercises.controllers.ApplicationController.library(libraryName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:32: Inferred type containing Serializable
[warn] GET /:libraryName/:sectionName  org.scalaexercises.exercises.controllers.ApplicationController.section(libraryName: String, sectionName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes:35: Inferred type containing Serializable
[warn] GET /progress/library/:libraryName/section/:sectionName org.scalaexercises.exercises.controllers.UserProgressController.fetchUserProgressBySection(libraryName: String, sectionName: String)
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] /Users/pawan/git/github/scala-exercises/server/conf/routes: var is disabled
[warn] 225 warnings found
[warn] 11 warnings found
[info] Compiling 12 Scala sources to /Users/pawan/git/github/scala-exercises/client/target/scala-2.11/classes...
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:186: abstract type pattern A is unchecked since it is eliminated by erasure
[warn]     def all[A <: dom.Element]: Seq[A] = j.toArray().collect { case d: A ⇒ d }
[warn]                                                                       ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Api.scala:26: null is disabled
[warn]     val parsedBody = read[SectionExercises](raw)
[warn]                                            ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Api.scala:53: null is disabled
[warn]     Ajax.postAsJson(url, write(request)).map(r ⇒ {
[warn]                               ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Effects.scala:29: throw is disabled
[warn]       val (lib, sect) = libAndSection
[warn]                         ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Model.scala:15: Function has default arguments
[warn] case class ClientExercise(
[warn]                          ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Ui.scala:92: Function has default arguments
[warn]   def setExerciseStyle(method: String, style: ExerciseStyle, codeStyle: String = ""): IO[Unit] = (for {
[warn]       ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Ui.scala:56: throw is disabled
[warn]     e.state match {
[warn]       ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/Ui.scala:82: throw is disabled
[warn]       val (arg, input) = argAndInput
[warn]                          ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/common/ExtAjax.scala:14: Function has default arguments
[warn]   def postAsForm(
[warn]       ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/common/ExtAjax.scala:25: Function has default arguments
[warn]   def postAsJson(
[warn]       ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/common/ExtAjax.scala:36: Function has default arguments
[warn]   def apply(
[warn]       ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/messages/Exercises.scala:19: Function has default arguments
[warn] case class EvaluationResult(
[warn]                            ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/scripts/ExercisesJS.scala:46: Statements must return Unit
[warn]       actions.onNext(action)
[warn]                     ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/scripts/ExercisesJS.scala:50: Statements must return Unit
[warn]       ui.foreach(ioAction ⇒ {
[warn]                 ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/scripts/ExercisesJS.scala:53: Statements must return Unit
[warn]       effects.foreach((f: Future[Option[Action]]) ⇒ {
[warn]                      ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:35: Inferred type containing Any
[warn]     $("pre").each((_: Any, code: dom.Element) ⇒ {
[warn]                                               ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:43: Inferred type containing Any
[warn]     $(".modal-body").each((_: Any, el: dom.Element) ⇒ {
[warn]                                                     ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:188: asInstanceOf is disabled
[warn]     def get[A <: dom.Element]: A = j.get().asInstanceOf[A]
[warn]                                            ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:197: asInstanceOf is disabled
[warn]   implicit def jQueryToModal(jq: JQuery): BootstrapModal = jq.asInstanceOf[BootstrapModal]
[warn]                                                               ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:35: Statements must return Unit
[warn]     $("pre").each((_: Any, code: dom.Element) ⇒ {
[warn]                  ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:43: Statements must return Unit
[warn]     $(".modal-body").each((_: Any, el: dom.Element) ⇒ {
[warn]                          ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:51: Statements must return Unit
[warn]     $(e).attr("class", s"exercise $style")
[warn]              ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:57: Statements must return Unit
[warn]     $(e).attr("class", s"exercise-pre $style")
[warn]              ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:63: Statements must return Unit
[warn]     $(e).find(".log").text(msg)
[warn]                           ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:78: Statements must return Unit
[warn]   def showSignUpModal: IO[Unit] = io($("#mustSignUp").modal("show"))
[warn]                                                            ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:85: Statements must return Unit
[warn]     $(input).keyup((e: dom.KeyboardEvent) ⇒ {
[warn]                   ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:103: Statements must return Unit
[warn]     $(exercise).find(".compile button").click((e: dom.Event) ⇒ {
[warn]                                              ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:29: throw is disabled
[warn]     nodes foreach { case (n, r) ⇒ $(n).html(r) }
[warn]                   ^
[warn] /Users/pawan/git/github/scala-exercises/client/src/main/scala/utils/DomHandler.scala:89: throw is disabled
[warn]         exercise ← OptionT(io(findExerciseByMethod(methodName)))
[warn]                  ^
[warn] 29 warnings found
[info] Fast optimizing /Users/pawan/git/github/scala-exercises/client/target/scala-2.11/client-fastopt.js
[info] application - Creating Pool for datasource 'default'
[info] p.a.d.DefaultDBApi - Database [default] connected at jdbc:postgresql://192.168.99.100:2345/scalaexercises_dev
[warn] application - application.conf @ file:/Users/pawan/git/github/scala-exercises/server/target/scala-2.11/classes/application.conf: 11: application.secret is deprecated, use play.crypto.secret instead
[info] play.api.Play - Application started (Dev)
Request from domain: localhost
Redirect : false
Values : previewApp:false, Play.isProd:false, request.secure:false, inWWW:false

Environment:
OS: Mac OSX 10.11.3
Scala: 2.11
Browser: Chrome Version 51.0.2704.106 (64-bit)

**Comment by juanpedromoreno** [comment]
Thanks for reporting it @pawank .

This issue is still pending to be fixed. In the meantime, you could do a quick fix locally replacing this line:

https://github.com/scala-exercises/scala-exercises/blob/master/build.sbt#L103

for `.dependsOn(core.jvm)`

and uncommenting this other one:

https://github.com/scala-exercises/scala-exercises/blob/master/build.sbt#L121

Hope it helps.

**Comment by pawank** [comment]
Perfect.. it worked.

**Comment by pawank** [comment]
Above workaround fixed it.
