### ISSUE TITLE
Mix code from exercise asserts with responses to be able to reference values and bindings

### ISSUE THREAD

**Issue by jdesiloniz** [scala-exercises/scala-exercises#572]
When posting requests to the remote evaluator, right now we're only performing calls to the defined asserts. This doesn't allow users to reference fields or values defined inside the scope of the exercise asserts, which would be ideal.

Maybe this could be doable by recreating the assert function, and the subsequent call to it in the request to the remote evaluator.

**Comment by rafaparadela** [comment]
We can focus on fixing this under the context of https://github.com/scala-exercises/scala-exercises/issues/530
