### ISSUE TITLE
Disable Disqus in Preview apps

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#573]
Disqus seems to be displaying ads. Let's get rid of them on preview apps if the cause it's the host. We want no ads in Scala Exercises.

**Comment by raulraja** [comment]
This is now happening in production too and it's unacceptable. @rafaparadela since you setup and have control over the discuss admin. Can you disable these? Otherwise we are gonna be forced to remove it from Scala Exercises all together. 
<img width="1420" alt="screen shot 2016-08-23 at 8 51 15 pm" src="https://cloud.githubusercontent.com/assets/456796/17917716/c526f96e-6973-11e6-8304-8c2ce1ea477b.png">

**Comment by raulraja** [comment]
https://engagingcomms.com.au/remove-disqus-ads-around-the-web-links-spam/

**Comment by rafaparadela** [comment]
Done.
