### ISSUE TITLE
Add Gitter embeded and remove disqus comments

### ISSUE THREAD

**Issue by raulraja** [scala-exercises/scala-exercises#591]
Discuss comments are proving to not have much value as library authors are not monitoring them and users are not getting the help they need.

We are going to make the following changes.
1. Add a Scala Exercises Gitter embed in the home page for the scala exercises project.
2. Add each library gitter as an embed in sections of that library. This should bring some new users to libraries as they work through the exercises and they can just pull out the chat and interact with community members in place.
3. Get rid of disqus all together.

We can derive the gitter room from the github url that is part of the compilation metadata.

For reference https://sidecar.gitter.im/

**Comment by rafaparadela** [comment]
I would add another subtask:

- Remove the integration with Disqus.

**Comment by raulraja** [comment]
Sounds good.
