### ISSUE TITLE
Pasting answers does not trigger field resize and Run button

### ISSUE THREAD

**Issue by scott-nance** [scala-exercises/scala-exercises#606]
**Description:**
  When pasting data into an answer checkbox, the field resize does not happen and the Run button does not activate. 

**Repro Steps:**
   1)  Pick a question, any question
   2)  Select text from the problem above "We just encountered an awesome Woodchuck Stampede!" and Copy
   3)  Paste the text into the answer box

**Observed Behavior:**
  1)  The answer field does not resize to show the entire text
  2)  The Run button does not enable

**Expected Behavior:**
  1)  The answer field should resize to show the entire text
  2)  The Run button should enable

**Notes:**
  The event that triggers these two changes appears to be based on keystrokes that change the contents of the field, because changing focus with the mouse or Tab key does not cause an update.

If possible the updates should be triggered by a text/contentChanged event, so that any changes to the contents of the field would trigger the updates.

**Comment by dialelo** [comment]
Good catch, and thanks for the detailed issue report!

**Comment by jdesiloniz** [comment]
@scott-nance Thanks for such a detailed report! I've been able to reproduce the resizing problems when pasting text into the inputs of each exercise, and I've sent a PR that hopefully fixes it.

But I haven't been able to reproduce your issues with the activation of the "Run" button. Were you logged in with GitHub when trying it? Also, was there a unique input in the exercise? (as the Run button only activates when all inputs are filled).
