### ISSUE TITLE
Server not starting (stuck on Loading project definition from)

### ISSUE THREAD

**Issue by chrissound** [scala-exercises/scala-exercises#646]
Either it's taking a while, or it's appears to be stuck:
```
sbt -v server/run
[process_args] java_version = '1.8.0_121'
# Executing command line:
java
-Xms1024m
-Xmx1024m
-XX:ReservedCodeCacheSize=128m
-XX:MaxMetaspaceSize=256m
-jar
/usr/share/sbt/bin/sbt-launch.jar
server/run

[info] Loading project definition from /home/chris/Projects/Scala/scala-exercises/project
```
`sudo netstat -lntu | grep 9000` returns no output.

**Comment by eperinan** [comment]
Hi @chrissound 

I had the same problem than you. In my case, I solved it increasing the memory to 2G with the following command in my `~/.profile`

`export _JAVA_OPTIONS="-Xms2G -Xmx2G -XX:ReservedCodeCacheSize=128m"`

Please check this and let me know if it works fine for you.

**Comment by AdrianRaFo** [comment]
Try `sbt -mem 2048` to increase the memory

**Comment by ysusuk** [comment]
Thanx @AdrianRaFo!
