### ISSUE TITLE
Logon problem on narrow window

### ISSUE THREAD

**Issue by kastoestoramadus** [scala-exercises/scala-exercises#660]
I got FHD screen in pivot. I am unable to login. Clicking the button doesn't change anything.

![image](https://user-images.githubusercontent.com/6271645/27326896-b8598da0-55a4-11e7-9409-4417f5ee1224.png)

Browser: Opera 45
OS: Ubuntu 16.04

**Comment by kastoestoramadus** [comment]
Moving window to second screen that has horizontal orientation enables to login.

**Comment by eperinan** [comment]
This bug is the same that mentioned @AdrianRaFo in the issue #658 

I've just created a PR to solve it https://github.com/scala-exercises/scala-exercises/pull/661

Thanks for report it
