### ISSUE TITLE
Still not able to run Exhaustivity (Scala Structuring Information)

### ISSUE THREAD

**Issue by andys8** [scala-exercises/scala-exercises#663]
Exhaustivity can't be run. Should be possible with #619 but I can't confirm it and there are more people having trouble (disqus, github issue).

https://www.scala-exercises.org/scala_tutorial/structuring_information

![img_0092](https://user-images.githubusercontent.com/13085980/28633964-ddfb4b40-7235-11e7-9806-ff5816e18feb.PNG)

**Comment by andys8** [comment]
[Here](https://www.scala-exercises.org/scala_tutorial/classes_vs_case_classes) is another one. The last block contains only `()` and can't be executed.

**Comment by AdrianRaFo** [comment]
Maybe we need to update the version and publish a new release because the last exercise is in the code, the `lazy evaluation` was fixed and still with the same error

**Comment by andys8** [comment]
@AdrianRaFo Do you know who will do the release?

**Comment by andys8** [comment]
[And another one](https://www.scala-exercises.org/scala_tutorial/lazy_evaluation)
<img width="1084" alt="screen shot 2017-08-05 at 16 22 43" src="https://user-images.githubusercontent.com/13085980/28996151-5bf050ce-79fa-11e7-8f7b-ca5112e80bfb.png">

**Comment by AdrianRaFo** [comment]
Sorry, I don't know but it has other problems so maybe we should wait until be fixed to launch a new release

**Comment by raulraja** [comment]
Was the version ever updated? I can do a new release that gets the latest snapshots if the exercise was fixed. Is there a PR where this was fixed @AdrianRaFo?

**Comment by AdrianRaFo** [comment]
I launched a pr that fixed a error in one of the exercise but I think that the new release wasn't launched when the exercises were fixed

**Comment by raulraja** [comment]
Is it included here: https://github.com/scala-exercises/scala-exercises/pull/665 ?

**Comment by AdrianRaFo** [comment]
That pr update the library to `0.4.2-SNAPSHOT` but the next release on scala tutorial should be `0.4.1-SNAPSHOT`

**Comment by raulraja** [comment]
@dominv can you include these changes it in the next master build? thanks

**Comment by juanpedromoreno** [comment]
`0.4.2-SNAPSHOT` supersedes to `0.4.1-SNAPSHOT`, the current code at https://github.com/scala-exercises/scala-exercises/pull/665 will release our latest changes across all libraries. Hence, the next deployment will upgrade the entire platform.

**Comment by dominv** [comment]
@raulraja I'm working on it. I'll deploy it ASAP

**Comment by raulraja** [comment]
@dominv thanks!

**Comment by dominv** [comment]
Scala-exercises has already been deployed. @andys8 @AdrianRaFo could you please check that this issue has already been fixed? Thanks!

**Comment by andys8** [comment]
@dominv Looks fine for "Scala tutorial" :+1: 

![image](https://user-images.githubusercontent.com/13085980/29169317-c258c54e-7dd3-11e7-84eb-e0efcab4da9b.png)

**Comment by dominv** [comment]
@andys8 Thanks! If everything is OK I'm going to close this issue. 👍
