### ISSUE TITLE
Can't press 'Run' button

### ISSUE THREAD

**Issue by alexanderyellow** [scala-exercises/scala-exercises#664]
Made exercise and 'Run' button is disable.

Screenshot:
http://joxi.ru/8236K6BH69wNam

**Comment by bowerth** [comment]
same here - not related to https://github.com/scala-exercises/scala-exercises/issues/471

**Comment by bowerth** [comment]
hi Alex - I figured this one out: 
1) you need to log in to your github account to see the "Run" button.
2) clone and execute the remote evaluator if you are serving from localhost:9000, see https://github.com/scala-exercises/evaluator#run-from-sources

**Comment by themanifold** [comment]
I came across this problem too, and found the same solution. Would be nice if there was a hint at what to do...

**Comment by juanpedromoreno** [comment]
Fixed in https://github.com/scala-exercises/scala-exercises/pull/668

**Comment by vermi4elli** [comment]
Btw, this problem can also occur if the AdBlock is enabled on the site, easy fix :)

**Comment by FarsanRashid** [comment]
The run button is not working again.
