### ISSUE TITLE
Investigate need for 2nd evaluator instance

### ISSUE THREAD

**Issue by justinelsberry** [scala-exercises/scala-exercises#669]
Currently, we have 2 Heroku nodes running the evaluator.  Because Kazari needs to evaluate both code on 2.12 and 2.11 we have 2 separate instances. With the removal of Kazari, we can kill one instance and save significant costs.

**Comment by raulraja** [comment]
@dominv @anamariamv Can you verify in Heroku what is the current instance of the evaluator not in use so we can kill it?

**Comment by dominv** [comment]
Scala Exercises is currently using the 2.11 version of the evaluator. AFAIK the 2.12 version it's being used only by the Freestyle's docs.

**Comment by justinelsberry** [comment]
@dominv Do the freestyle docs **Need** the 2.12 version?

**Comment by raulraja** [comment]
@justinelsberry I shutdown the 2.12 instance
