### ISSUE TITLE
uBlock Origin blocks "run" button

### ISSUE THREAD

**Issue by aint** [scala-exercises/scala-exercises#683]
It looks like that uBlock Origin makes the "run" button always disabled.

Console output:
```
Loading failed for the <script> with source “https://www.scala-exercises.org/javascriptRoutes”.
terms_and_types:827
Source map error: request failed with status 403
Resource URL: https://sidecar.gitter.im/dist/sidecar.v1.js
Source Map URL: sidecar.js.map[Learn More]
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://3d4d85bb-e895-e74a-89dd-f34b29fa617c/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map[Learn More]
```

Reproduced on Firefox 60.0.2 and Chrome 67.0.3396.87 with uBlock Origin.
Meanwhile no issue with Safari 11 without any extensions.

![untitled](https://user-images.githubusercontent.com/3179252/41499904-907e70c0-7191-11e8-8862-9c0f59e6b35b.gif)

uBlock Origin enabled filters:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/3179252/41499957-2a002e28-7192-11e8-8e81-556dcf4a3816.png">

**Comment by FRosner** [comment]
Thanks for creating this detailed issue @aint :)

@raulraja any clue why `https://www.scala-exercises.org/javascriptRoutes` gets blocked and if this could be the reason? The gitter sidecar shouldn't be a problem. Not sure about the polyfill.

@aint can you see from within uBlock origin which files are blocked exactly?

**Comment by aint** [comment]
So for some reason `RU AdList` has a rule that blocks `javascriptRoutes` 

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/3179252/41501241-4a1ee480-71a9-11e8-83b2-2147da4f0d17.png">

**Comment by calvellido** [comment]
Hey @aint, having a look to the regex causing that block I have checked that any script being fetched from an URL with a path longer than 15 chars will be blocked. You can test

```
/^https?:\/\/[^/]+\/[a-z0-9]{15,}(\?hope=.*)?$/$script,domain=~coco.fr|~sap.com|~studio-svet.ru|~stumbleupon.com|~tv.yandex.by|~tv.yandex.kz|~tv.yandex.ru|~tv.yandex.ua
```

here:

https://regex101.com/


Also, you can easily see that other Play Framework sites will get blocked that `javascriptRoutes` path too (https://krispii.com/).

I have also tested on a personal site:

![captura de pantalla de 2018-06-19 15-00-06](https://user-images.githubusercontent.com/7753447/41598772-831bc15c-73d1-11e8-80eb-d64b047b9244.png)

![captura de pantalla de 2018-06-19 15-03-14](https://user-images.githubusercontent.com/7753447/41598907-eb3282c6-73d1-11e8-956a-d7ac5146b6f8.png)


If you want to use Scala Exercises keeping your current settings, please deactivate that faulty list, or submit a better regexp to the maintainers of RU AdList (https://forums.lanik.us/viewforum.php?f=102)

Thanks!

**Comment by FRosner** [comment]
Thanks for looking into this @calvellido!
