### ISSUE TITLE
a problem in formatting exercises 

### ISSUE THREAD

**Issue by markwhitey** [scala-exercises/scala-exercises#691]
# Character Literals can be an escape sequence, including octal or hexidecimal:
```diff
val c = 'a' //unicode for a
- val d = '\141' //octal for a
val e = '\"'
val f = '\\'
```
---
# There are problems:
**Error:(83, 12) octal escape literals are unsupported: use \u0061 instead
  val d = '\141' //octal for a**

**Comment by juanpedromoreno** [comment]
I believe this is fixed now: https://www.scala-exercises.org/std_lib/literal_strings

Please, feel free to reopen in any other case.
