### ISSUE TITLE
Running the exercises seems to be broken?

### ISSUE THREAD

**Issue by cb372** [scala-exercises/scala-exercises#696]
e.g. filling in the blanks in the first exercise on https://www.scala-exercises.org/cats/semigroup and clicking 'Run' results in an error:

```
Evaluation failed : Compilation Error ; ERROR -> not found: value catslib at [213, 213, 213]
```

I tried one of the stdlib exercises and got a similar error.

**Comment by calvellido** [comment]
It should be back now @cb372, thanks for reporting it!
