### ISSUE TITLE
Upgrade all the things

### ISSUE THREAD

**Issue by cb372** [scala-exercises/scala-exercises#697]
It looks like scala-exercises is in need of some love. It's using very old versions of Scala, sbt, Play and probably many other libraries.

**Comment by calvellido** [comment]
Hey @cb372, thanks for the suggestion.

Indeed, we are in the process of updating the project and all its dependencies, you will see the results of this in the coming months.

**Comment by cb372** [comment]
Great! Let me know if you want any help.

**Comment by juanpedromoreno** [comment]
The upgrade has been completed today 🚀 

Thanks @kiroco12 for your work here.
