### ISSUE TITLE
evaluate endpoints are returning 503s.

### ISSUE THREAD

**Issue by davisharlan** [scala-exercises/scala-exercises#713]
e.g. https://www.scala-exercises.org/exercises/sections/cats/foldable/evaluate is unavailable.

**Comment by kiroco12** [comment]
I posted in gitter the service was restarted and it looks to be working. I'm currently updating all projects (including evaluator) and fix will be applied in the next days.

**Comment by davisharlan** [comment]
It looks good now. Should this be closed?

**Comment by calvellido** [comment]
Thanks @davisharlan :+1:
