### ISSUE TITLE
Handle Github authentification when compiling + frontend code

### ISSUE THREAD

**Issue by LePuppy** [scala-exercises/scala-exercises#714]
Hi,
I am very new in Scala. I cloned the scala-exercises repo in order to create a custom Scala tutorial based on the project's architecture. However, I face two issues :

1) When compiling, Github authentification is asked and redirects to error page. How can I correct this or disable the authentification when compiling ?

2) It may sound stupid but I can't manage to find frontend code in order to try modifying text / tests. Where should I look into ?

Thanks :)

**Comment by kiroco12** [comment]
Hello! For the first question, you have to set an env variable called `APPLICATION_URL` to set the redirection url used in the github api ("http://localhost:9000" should be good). By default is set to https://www.scala-exercises.org. To answer the second question, I'm doing backend development to this project, you can find scala html files in server/app/views/templates, scss files in server/app/assets/stylesheets and the project client based in scalajs.
