### ISSUE TITLE
503 - broken exercises

### ISSUE THREAD

**Issue by grzegorz-bielski** [scala-exercises/scala-exercises#866]
Hi!

Looks like the `/evaluate` returns `503`, at least for the `Std Lib` and `Scalacheck` courses, I haven't tried the others. 

HAR file from Firefox 82.0b2: https://pastebin.com/4du8U1fC

**Comment by juanpedromoreno** [comment]
Thanks for reporting @grzegorz-bielski , it should be fixed now. Please, feel free to reopen if the problem returns.
